In [1]:
import numpy as np
import pandas as pd

Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0,100] e exiba os valores e o tipo de dado do array

In [4]:
arr = np.random.randint(0,100, size=(10))
print(arr)
print(arr.dtype)


[98 40 68 36 12 87 40 20  1 83]
int64


Crie uma matriz 5x5 com valores aleatórios de [0,1] e encontre o valor mínimo, máximo e a media da matriz

In [11]:
arr = np.random.rand(5,5)

print(arr)

print("Minimo: ", arr.min())
print("Maximo: ", arr.max())
print("Media: ", arr.min ())





[[0.58942026 0.20518549 0.62153763 0.34004138 0.2695234 ]
 [0.43437438 0.84338819 0.71951062 0.55334725 0.05934781]
 [0.22556715 0.30604046 0.25375812 0.90084256 0.52767963]
 [0.34114857 0.37525974 0.31877332 0.80835615 0.97162118]
 [0.82818835 0.02674539 0.78013043 0.41658185 0.63947314]]
Minimo:  0.026745387028094814
Maximo:  0.9716211772966367
Media:  0.026745387028094814


Crie um array com 10 elementos aleatórios no intervalo [0,1] Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro

In [14]:
arr = np.random.rand(10)

arr2 = arr * 10

arr2_convert = arr2.astype(int)
print(arr)
print(arr2_convert)


[0.31042211 0.44926032 0.32416684 0.74173972 0.21047048 0.04756773
 0.44511395 0.13520111 0.36669082 0.99506402]
[3 4 3 7 2 0 4 1 3 9]


Crie um array de duas dimensões com shape(3,3) e valores aleatórios inteiros no intervalo [0,9]. Substitua todos os elementos da segunda linha por -1

In [19]:
arr = np.random.randint(0,9, size=(3,3) )

print(arr)
print("__________________")

arr[1] = -1

print(arr)

[[1 6 4]
 [8 3 5]
 [6 8 2]]
__________________
[[ 1  6  4]
 [-1 -1 -1]
 [ 6  8  2]]


Crie um DataFrame com as seguintes informações:
Coluna Fruta: Banana,Maça,Pera
Coluna Preco: 7.90,10.20,11.80
Coluna Quantidade: 12,3,4

In [21]:
hortifruti = {
  "Frutas": ["Banana", "Maça", "Pera"],
  "Preço": [7.90, 20.30, 22.80],
  "Quantidade": [12, 3, 4]
}
hortifruti = pd.DataFrame(hortifruti)

print(hortifruti)

   Frutas  Preço  Quantidade
0  Banana    7.9          12
1    Maça   20.3           3
2    Pera   22.8           4
